# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ?? (???? ??? ?? ???? ?? ??)
      location: C:\Users\Playdata\Desktop\Spring\springBoot\uploadFiles
      # ?? ??? ?? ??
      max-file-size: 10MB
      # ?? ?? ?? ??
      max-request-size: 10MB