# yml 형식으로 저장
spring:
  servlet:
    multipart:
      # 이미지가 저장되는 경로
      location: C:\SpringBoot\uploadFiles
      # 최대 업로드 파일 크기
      max-file-size: 10MB
      # 최대 요청 파일 크기
      max-request-size: 10MB